#10jan2022 found bug in F focus
# when no items selectedm action was supposed to focus on ALL
# my testing was done by manually selecting all (ctrl shift met l l=clk in space)
# and then typing F
# nononono the litany is   dbl clk in space ( insures nobody selected)
# then F
# i got error for var used before assign value
# to fix i assigne slef.screnRect() to the area var
#
#09jan2022 2348
# i chgd to cnxnSide , and edited hal2json so it knew to use cnxnSide also
# i t testes and found grid screwed up becuz renum cnum were not ints 
# fixed the grid problem
# loaded the grid ratsnest and wheni tried to edit cnxnside or index into stack
# i got a blanl scite page...
#  the filename was hardcoded as 'SaveMe'  no path, not fqfn
# so i chcgd from loadinf 'SaveMe' to loading 'workingFile'
# worked  ( so far )
# enuf for today  midnoght
#
#09jan2022 scaling up down ng,,, soemtimes goes wring direction
#  exampe press + 7 time, press - 7 times repeat, watch screen
#
#09jan2022 chg dflt soom incr from 1.15 to 1.1  was 1.03 orig, so now in between-ish
# 
#09jan2022 i got fesls for save and load
# and i can use that to save 'views'
# TODO    LOTS of cleanup
# some organization is on user's responsibility
# creating workingfolders is good idea
# and inside the working folder could be a views folder
#
# TODO when saved the zoom factor at save time is not reinstated
#   instead, the last zoom factor is applied
#   also the location is left shifted ( at least left , maybe up/down too )
# 
#   the file saved has no place for viewctr or view scale (yet)
#   i dunno where 0,0 is really, i THINK its top left of scene
#   i THINK all coord are in the X+ Y+ quadrant  which is quadrant 4 of normal maths, but acts like quadrant 1 ( Y+ goes down, go figger!)
#   
#  if i add a section ZOOM to SaveMe, are there any tools already fro translation and scaling?
#
#09jan2022
# DONE saved views vs enter/exit hierarchical sheets
#
# ctrl shift meta l press selects all
#
#  i still dont understand signals and slots  enuf
#
#05jan2022 the system is near done for 2 of 3 stages
# 1)read and parse file from halcmd show pin  
#    into dicts and lists
#    into format used bu Nodz (json CONNECTIONS and NODES)
# 2)load json into Nodz and render the graph
#    DONE space out the nodes when created
#    use a grid of 400x600 and 2x2,3x3,4x4 grid accordung to numNodes
#    BUG there is a prblem when position is 0,0, the node ends up ctrd in scene
#     not at 0,0, as workaround i set 0,0 to 1,1
#    i think err is in createNode in 'if not position"
#     because that code puts node in scene center
#    i think that logic fails when valid posn is 0,0
# DONE there were some pin sources missing in the hal file
# i think way back at .hal ( further than  halcndShowSig file level )
#  yes 2 src missing for randomGV
#  the thresholds are pins, why not in show sig?
#  well they have no sig they have pins and are inputs
# look at hal src, nowhere in hal or hal2
# IS in M196
#halcmd setp randomGV.GvHiThreshold $1
#halcmd setp randomGV.GvLoThreshold $2
# so maybe cnx the pin to a signal... 
#   maybe that will create the dummy source node(s)
# linksps ??  or net  s  p
# YES in hal/hal2  use net from pin to signal
#   signal goes NOWHERE but hal2graph sees that and creates a node
#   same idea works for ouput signls w/o destination obj
#    just add a signal to the outpin and hal2graph will create a dest node
# these autogenerated nodes use signalnameSOURCE or signalnameDEST as nodename
# 3) TODO save the file as .hal
# 
#05jan2020
# de-select all:  l press in space (dbl clk not necc but works )
# select all   :  ctrl shift meta l l press in space
# select group :  shift l press (or ctrl shift l press) & drag over grou[p
# deselect 1 node from group: shift l press on node until its border dims ( deselected)
# add 1 item to group: shift l press on node untill its border hilites (becomes selected)
# i achieved this by banging the code--- i need to understand the flow
#  which has to do with several states that are set up
# during say a double clk
# a dbl clk is actually a press, a release, a pressm another release
# and during those events the keyboard modifier may have occured
# shift control meta modifiers work  ALT DOES NOT WORK AS MODIFIER ?? xfce? dunno could not chg ALT reaction of xfce4 settings
#
#04jan 1519 its VERY HARD to cnx a bez to a plug
# DOH i was on a socket
# its easy to drag from a plug, go inside node a bit , say 2mm
# you should see the bex test pop out the side right away
# (if over a plug and not a socket doofus!)
# doh   i was on a socket   some viz indicator is good
#
# EDITING NODE using SCITE 
# 09jan2022 FIXED call is clean now and a single wndo opens w scite
#  and a single wndo needs to be closed/exited
#
# TIP when chging order of pins, 
#  in the editor, just grab the INSIDES of the { ... }
# and move that,  this avoid  cleaning up the }.
# so far all editing is pin posn in stack and cnxnSide
# but alternate will happen too
#
#TODO spcl to ctr focus at click
#
# TODO:
#  zoom and pan are not nice
#  its hard to get at some parts of dwg
#  and if not zoomed in enuf, its easy to accidental clk & delete a net
# TIP: to avoid accidentaly removong nets
#   zoom way out to see all
#   lasoo all
#   zoom IN before grabbing the group
#   then its easy to NOT erase a net, and to move the group
#   re-position the group so the area of interest is central
#   then zoom in to work
# 09jan2022 TODO
# the accidental net removal could be handle by avoiding
#  the action needed to delete the net
#  if a special modifier combo was required
#  then the accidents will decrease 
#
# TODO testing:  test other poeples suites
# i can brows other lcnc cfg suites 
#   and run halcmd show sig > blahShowPins
#   then look at graphs ( run parseHal , run nodz_demo)
#
#09jan TODO
#   if i open a 3rd wndow ( 2popups from main wndo) 
#    the 1st popup wndo dissappears
#    can i get more than 1 child window?
#
# TODO default viewers in cfg file
#  like others may not use ffox or scite or have spcl svg viewer
#
#16dec
# DONE make the subgraph for arduino subsystem (filename test2) (file test3 no longer used)
#
#14dec hover popups works well\
# also fund out the parents of classes
# ---class----------------parent--------
# ,-Nodz		QtWidgets.QGraphicsView 
# |   NodeScene		cant clk on it theres nothing to clk on
# |-background		Nodz
# |-NodeItem		NodeItem & Nodz
# | ,-SlotItem------,	no response when clk on the horiz area i think is slot
# | |-PlugItem------|	SlotItem PlugItem
# | `-SocketItem-,  |	SlotItem & SocketItem
# |    on DOT----`--`	SlotItem &(PlugIten or SktItem) depending on dot
# `-ConnectionItem	Nodz & CnxnItem
#
#05dec2021
#while walking 'boots' the chihuahua, i had a vision
# and i mean vision becuz i see an image in my mind, not words or some linear thog=ught process
# iwas surprised to know that my thought process was basically visual
#
# anyway the image was of somecode on the screen'
# and it was about a class and was a response to an evene
# there were mayby of these in the real code
#so my image.thought was, thats the way to see how to get the hiddenthisnode.alternate info
# becuz i remembered that some classes had such code
# so now go look for such
#
# it looks like in nodz_main class NodeItem mouseDoubleClickEvent
#
#03dec2021 i had an imagining, that if i clicked on a widget
# that was a 'meta'widget' ( a comination of several widgets with just the i/o exposed)
# i imagined the meta widget would simply load a different file and render it 
# this new file would be the digraph of the metawidget, in simple widgets
# 
# TODO collect the TODOs scattered thry code and put here
#
#
#TODO  different colors for diff dataType pins, maybe nets too
#
#
#   RULE: ALWAYS set socketMaxConnections to 1 ( no more than 1 )
#   RULE always set plugMaxConnections to -1 ( infinite_

# There is a file describing the scene
#  the file has 2 parts ,  Nodez  and Connections
#  Connections is a list of pairs of slots/pins
#  Nodes is a multi level dictionary with an entry for each widget/compe/node
#   each Node has a list of pins/slots
#     each slot/pin has a dict of properties 'attributes'

from PyQt5 import QtCore, QtWidgets
import nodz_main

try:
    app = QtWidgets.QApplication([])
except:
    # authors note:  I guess we're running somewhere that already has a QApp created
    app = None

nodz = nodz_main.Nodz(None)
nodz.initialize()
nodz.show()

# 06nov2021  heavy handed global aliasing  found on web as 'cure' for pyqt5
QtCore.Signal = QtCore.pyqtSignal
QtCore.Slot = QtCore.pyqtSlot
QtCore.Property = QtCore.pyqtProperty

######################################################################
# Test signals
######################################################################

#08jan2022  this weird @thing
# this is how the Slot s are defined  ( real qt slots )
# in some other place, a signal will be created 
#  and in yet anpthe place, the signal will be emit-ed
#  and the signal will need to be connected to the slot

@QtCore.Slot(str)
def on_nodeSelected(nodesName):
    #print('node selected : ', nodesName)
    #09jan2022  why did i cut off nodesName?
    print('node selected')

#08jan try to make a new SLOT 
#  it will need a signal and the signal need to be emit-ed
#  and the signal and slot will need to be connected
#09jan2022 TODO i dont see these texts printed in console
@QtCore.Slot(str)
def on_plugSelected(plugName):
    print('plug selected : ', plugName)
    #08jan vvv no effect  no print
    sender = self.sender()
    print("sender is ", sender.text())

#04jan2022 i do NOT get this msg printed to console when i dbl clk a node
# but i DO get the ShowMe action ( nothing in console tho)#
#09jan2022 this doesnt print, i dont have signal,slot,connect setup correct
@QtCore.Slot(str)
def on_nodeDoubleClick(nodeName):
    print('double click on node : {0}'.format(nodeName))

# Attrs

# Connections

def on_connected(srcNodeName, srcPlugName, destNodeName, dstSocketName):
    #09jan2022 harmless , likely doesnt print anyways
    # originally neutered to reduce clutter in console
    #09jan2022 there's a LOT of clutter removed
    # maybe be a good idea to reinstate, they show signals making iot thru system
    # a 'ifdef' type enable / debug level  could be coded
    print('in on_connected  connected src: "{0}" at "{1}" to dst: "{2}" at "{3}"'.format(srcNodeName, srcPlugName, destNodeName, dstSocketName))

@QtCore.Slot(str, str, str, str)
def on_disconnected(srcNodeName, srcPlugName, destNodeName, dstSocketName):
    print('disconnected src: "{0}" at "{1}" from dst: "{2}" at "{3}"'.format(srcNodeName, srcPlugName, destNodeName, dstSocketName))

# Graph

# Other
@QtCore.Slot(object)
def on_keyPressed(key):
    print('key pressed : ', key)

#04jan2022 these vvv connect SIGNAL to SLOT ( SLOTS ar ethe @Qtblah things above)
nodz.signal_PlugConnected.connect(on_connected)
nodz.signal_SocketConnected.connect(on_connected)
nodz.signal_NodeSelected.connect(on_nodeSelected)
nodz.signal_NodeDoubleClicked.connect(on_nodeDoubleClick)
nodz.signal_SocketDisconnected.connect(on_disconnected)
nodz.signal_KeyPressed.connect(on_keyPressed)
#08jan try to make a new sgl
nodz.signal_PlugSelected.connect(on_plugSelected)

######################################################################
# Test API
######################################################################
#21nov   all the info needed to construct the scene is in the SaveMe json file

# Graph

nodz.clearGraph()

if app:
    # command line stand alone test... run our own event loop
    app.exec_()
